###############
# 数据库信息
###############
db_host: !!str 127.0.0.1
db_user: !!str root
db_password: !!str viekk2423
db_database: !!str usavisa；

# wugf 专用链接， 别删除，可以注释掉
#db_host: !!str db
#db_user: !!str root
#db_password: !!str 111111
#db_database: !!str usavisa
###############
# 指定本系统可以处理的账号
###############
acct_type_cd: !!str ca_B #账号分类。 分类必须是数据库acct_type.acct_type_cd已经指定的信息
